### ISSUE TITLE
Add app integration ID into store for GH access tokens

### ISSUE THREAD

**Issue by jhosteny** [telia-oss/sidecred#21]
Hi @itsdalmo,

We need to be able to use access tokens with the [git-resource](https://github.com/concourse/git-resource), with private submodules. This works if you add the following config to the resource:

```
- name: repo
  type: git
  source:
    uri: https://github.com/<org>/<repo>.git
    branch: master
    username: 12345
    password: ((<org>-access-token))
    git_config:
      - name: "url.https://12345:((c<org>-access-token))@github.com/.insteadOf"
        value: "git@github.com:"
      - name: "url.https://.insteadOf"
        value: "git://"
```

I would like to be able to inject that app integration id as a var into SSM. I can take a shot at this one if you agree. Am I missing an easier way to handle this?
